### ISSUE TITLE
If function keeps spamming

### ISSUE THREAD

**Issue by RoxyBoxxy** [PolyLogiX-Studio/Neos.js#57]
Not sure if its my fault but when i type a command twice it spams me 3 times with the same message 
This is my code 
```js
    neos.on("messageReceived", (message)=>{
        
    if (message.Content = "/test") {
        neosvr.stdin.write('uptime\n');
        neosvr.stdout.on('data', function (data) {
        
        neos.SendTextMessage(message.SenderId, ""+ data)
    })
    }
    
       
})
```

**Comment by bombitmanbomb** [comment]
I tested it without the neosvr child process and it worked as intended, however from my experience working with the headless client, it returns data in chunks, things like getting the userlist and session info are multiline and emit multiple events to stdout. The above code also adds a new listener each time (they are not destroyed automatically) ontop of it will fire on a user joining, the world saving, etc.

**Comment by bombitmanbomb** [comment]
See [HeadlessGUI Data_Handler](https://github.com/PolyLogiX-Studio/HeadlessGUI/blob/2d5470e53ed078e2e49da9455cd68543de97ea2e/Server.js#L199) 

You will likely want to create a support function specifically for data emits. Being async it can be tricky however.

**Comment by RoxyBoxxy** [comment]
yer i wanted to make it send commands to the neos headless client and i was useing this 
```js
const { exec } = require("child_process");
var neosvr = require('child_process').spawn('bash');
```

**Comment by bombitmanbomb** [comment]
I have sent you some extra info in DM on Discord along with an event script. Interfacing with neosvr can be tricky.
