### ISSUE TITLE
 Cannot read property 'IsOK' of null

### ISSUE THREAD

**Issue by RaithSphere** [PolyLogiX-Studio/Neos.js#70]
Server is idle, no commands being pushed by myself.
Version: 1.6.17

/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:482
        if (cloudResult.IsOK) {
                        ^

TypeError: Cannot read property 'IsOK' of null
    at /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:482:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by bombitmanbomb** [comment]
Result of fix allowing Continuing Execution after on(error), will add fix by returning a null CloudResult object in next npm publish, i see you are on the self import GitHub build version, for now you can add on the line before
```js
if (!cloudResult) cloudResult = {isOK:false, state:500, Entity:{}}
```

**Comment by RaithSphere** [comment]
not had an issue with this pop up recenlty
